app:
  name: "driver"
  graceful_shutdown_timeout_seconds: 15

jaeger:
  addr: "jaeger:4317"

grpc:
  addr: ":84"

http:
  addr: ":80"

swagger:
  path: "third_party/swagger"

mongo:
  uri: "mongodb://driver-mongo:27017"
  auth_source: "admin"

kafka:
  group_id: "driver-service"
  brokers:
    - "kafka-1:9092"
    - "kafka-2:909"
    - "kafka-3:9092"
  driver_produce_topic: "driver-out"
  driver_consume_topic: "driver-in"

driver:
  offer_radius: 3.154

location:
  addr: "location:84"