app:
  name: "location"
  graceful_shutdown_timeout_seconds: 10

jaeger:
  addr: "jaeger:4317"

grpc:
  addr: ":84"

http:
  addr: ":80"

swagger:
  path:
    "third_party/swagger"

mongo:
  uri: "mongodb://driver-mongo:27017"
  auth_source: "admin"
